version: "3.3"
services:
  api:  
    image: codetenor/econtractor-api:latest 
    ports:
      - "8080:80"
    volumes:
      - eContractor-db:/app/database/sqllite
      - ./storage/local:/data/storage/local

  mobile-app:
    image: codetenor/econtractor-mobile:latest
    ports:
      - "3200:80"

  admin-app:
    image: codetenor/econtractor-admin-app:latest
    ports:
      - "4200:80"
  
volumes:
  eContractor-db:
    driver: local
